Add new locations for materials.mat
w23/xash3d-fwgs pull request #243
Opened 2021-11-30 15:42 UTC by 0x4E69676874466F78

pbr/sprites/materials.mat
pbr/gfx/env/materials.mat

2021-11-30 19:00 UTC, w23 reviewed
Ну и интерфейс в мобиле, я себе отломал все глаза и пальцы

2021-11-30 19:22 UTC, 0x4E69676874466F78 commented on ref_vk/vk_materials.c
> +	loadMaterialsFromFile( "pbr/gfx/env/materials.mat" );
Чтобы распределить материалы по типу. Спрайты в одном месте, небо в другом. Хотя с небом я возможно и правда поторопился. Как кубемапы будут грузиться? Будет ли для них параметр экспозиции чтобы можно было отрегулировать более тонко (нежели каждый раз проходить мучительно руками по каждой стороне в гимпе, хотя возможно cmftstudio позволяет задать экспозицию и с ней уже экспортировать, надо проверить.

2021-12-01 04:00 UTC, w23 requested changes

2021-12-01 04:00 UTC, w23 commented on ref_vk/vk_materials.c
> +	loadMaterialsFromFile( "pbr/gfx/env/materials.mat" );
Кубемапы будут грузиться просто из `pbr/env/<skyname>({bk,rt,...}.{png,tga,bmp}|.ktx2)`. Это то, как они сейчас грузятся (правда, без ктх).

Как делать экспозицию я хз. Вижу два варианта:
- подкладывать в каждую конкретную карту через патч
- подкладывать в, скажем, `pbr/env/<skyname>.info` _что-то_. Этим чем-то можно и существующие кубмапы попробовать вытянуть в хдр на коленке. Когда доберёмся до хдр и вот этого всего.

И да, вот так бы:
```suggestion
	loadMaterialsFromFile( "pbr/env/materials.mat" );
```

2021-12-01 10:39 UTC, 0x4E69676874466F78 commented on ref_vk/vk_materials.c
> +	loadMaterialsFromFile( "pbr/gfx/env/materials.mat" );
gfx там чтобы структуру держать такую же как в самой халфе, иначе не согласовано выходит, с другой стороны тут совсем другой формат уже, так что можно наверное и забить.

2021-12-01 10:40 UTC, 0x4E69676874466F78 commented on ref_vk/vk_materials.c
> +	loadMaterialsFromFile( "pbr/gfx/env/materials.mat" );
и да, зачем предложение если всё равно это не нужно и предлагается через info или patch?

2021-12-01 10:41 UTC, 0x4E69676874466F78 commented on ref_vk/vk_materials.c
> +	loadMaterialsFromFile( "pbr/gfx/env/materials.mat" );
Я тогда просто выпилю эту строку `loadMaterialsFromFile( "pbr/env/materials.mat" );` пока мы не разберёмся как это делать.
Сам думал в materials.mat просто в for задавать имя скайбокса и дальше ключи с параметрами.

2021-12-01 23:55 UTC, 0x4E69676874466F78 commented
Выпилил `loadMaterialsFromFile( "pbr/gfx/env/materials.mat" );`

2021-12-02 03:14 UTC, w23 approved these changes

2021-12-02 03:14 UTC, merged