Improved console commands
w23/xash3d-fwgs pull request #244
Opened 2021-11-30 17:53 UTC by 0x4E69676874466F78

Remove requirement -vkdebug for vk_rtx_reload, vk_rtx_reload_rad, vk_rtx_freeze; fix #68
Add vk_rtx command, fix #67

2021-11-30 18:58 UTC, w23 commented
Чушь какая-то. Вижу комменты с мобилы, а с веб-версии не вижу

2021-11-30 18:59 UTC, w23 requested changes

2021-11-30 18:59 UTC, w23 commented on ref_vk/vk_framectl.c
> +		}
```suggestion
		g_frame.rtx_enabled = CVAR_TO_BOOL( vk_rtx );
```

2021-12-01 03:52 UTC, w23 commented on ref_vk/vk_cvar.c
> +	vk_rtx = gEngine.Cvar_Get( "vk_rtx", "1", FCVAR_ARCHIVE, "Enable or disable ray tracing mode" );
По-хорошему это нужно делать после того, как мы поняли, что rtx вообще возможен на этой машине. Но это мендокусай какой-то.

2021-12-01 03:52 UTC, w23 approved these changes

2021-12-01 03:53 UTC, merged

2021-12-01 10:35 UTC, 0x4E69676874466F78 commented on ref_vk/vk_cvar.c
> +	vk_rtx = gEngine.Cvar_Get( "vk_rtx", "1", FCVAR_ARCHIVE, "Enable or disable ray tracing mode" );
Да я тоже об этом думал, но что-то у меня там вчера не вышло, щас попробую сделать с новыми знаниями.