Add ClearBits for FBitSet
w23/xash3d-fwgs pull request #247
Opened 2021-12-01 12:09 UTC by 0x4E69676874466F78

Because otherwise the condition will be called all the time.

2021-12-01 21:19 UTC, 0x4E69676874466F78 commented on ref_vk/vk_cvar.h
> +#define FCVAR_READ_ONLY		(1<<17)	// cannot be set by user at all, and can't be requested by CvarGetPointer from game dlls
Заинклудить cvar.h не могу, сыпет ошибками.

2021-12-01 21:20 UTC, 0x4E69676874466F78 commented on engine/common/cvar.c
> +	if( FBitSet( var->flags, FCVAR_READ_ONLY )) // TODO: fix order VK init render or fix this GL-eccentric
Грязное, но простое решение всех наших проблем на данном этапе. Это позволит писать в vk.cfg и настройки оттуда доступны на раннем этапе.

2021-12-01 23:42 UTC, 0x4E69676874466F78 commented on ref_vk/vk_cvar.c
> +	vk_rtx_extension = gEngine.Cvar_Get( "vk_rtx_extension", vk_core.rtx ? "1" : "0", FCVAR_READ_ONLY, "" );
Чтобы можно было скрывать настройки если rtx нам недоступно. 
Кстати говоря нужно ли нам ещё отдельно `-rtx`? 
Я считаю надо сделать логику если есть расширения у видюхи то автоматически включать режим с `rtx`.
С этими коммитами режим запоминается, даже при -rtx.

2021-12-01 23:43 UTC, 0x4E69676874466F78 commented on ref_vk/vk_cvar.c
> +		vk_rtx = gEngine.Cvar_Get( "vk_rtx", "0", FCVAR_READ_ONLY, "DISABLED: not supported without -rtx" );
Без `-rtx` будет пояснение что этот квар не работает и его не удастся изменить.

2021-12-01 23:47 UTC, 0x4E69676874466F78 commented on ref_vk/vk_cvar.c
> +	vk_rtx_extension = gEngine.Cvar_Get( "vk_rtx_extension", vk_core.rtx ? "1" : "0", FCVAR_READ_ONLY, "" );
Изначально я хотел чтобы без `-rtx` квар `vk_rtx` временно становился на 0 и его нельзя было изменить, но это оказывалось технически невозможно.

2021-12-02 00:02 UTC, 0x4E69676874466F78 commented on ref_vk/vk_framectl.c
> +	ClearBits( vk_rtx->flags, FCVAR_CHANGED );
Эту штуку надо ставить, иначе условие будет всё время выполняться.

2021-12-02 03:16 UTC, w23 commented on ref_vk/vk_cvar.c
> +		vk_rtx = gEngine.Cvar_Get( "vk_rtx", "0", FCVAR_READ_ONLY, "DISABLED: not supported without -rtx" );
Вообще `-rtx` аргумент это тоже костыль. Мне так было быстрее начать что-то делать.
Надо обсудить, как именно мы хотим рулить этим всем

2021-12-02 09:49 UTC, 0x4E69676874466F78 commented on ref_vk/vk_cvar.c
> +		vk_rtx = gEngine.Cvar_Get( "vk_rtx", "0", FCVAR_READ_ONLY, "DISABLED: not supported without -rtx" );
@w23 ну я выше написал свои мысли.

2021-12-02 22:31 UTC, 0x4E69676874466F78 commented on ref_vk/vk_cvar.c
> +		vk_rtx = gEngine.Cvar_Get( "vk_rtx", "0", FCVAR_READ_ONLY, "DISABLED: not supported without -rtx" );
Поправил текст. И обрати внимание на #251

2021-12-03 19:33 UTC, w23 requested changes
Нужно бы описание того, что тут и зачем.
И примерный сценарий, как оно живёт во времени и пространстве.

2021-12-03 19:33 UTC, w23 commented on ref_vk/vk_cvar.c
> +#include "vk_render.h"
```suggestion
#include "vk_core.h"
```

2021-12-03 19:43 UTC, 0x4E69676874466F78 commented on ref_vk/vk_cvar.h
> +#define FCVAR_READ_ONLY		(1<<17)	// cannot be set by user at all, and can't be requested by CvarGetPointer from game dlls
`FCVAR_READ_ONLY` используется для того чтобы требуемые квары не могли быть перезаписаны в консоли руками. При попытке перезаписать квар с флагом `FCVAR_READ_ONLY` консоль выдаст отказ "is read-only".

2021-12-03 19:54 UTC, 0x4E69676874466F78 commented on engine/common/cvar.c
> +	if( FBitSet( var->flags, FCVAR_READ_ONLY )) // TODO: fix order VK init render or fix this GL-eccentric
Если из данного участка не убрать `FCVAR_GLCONFIG` то квары с этим флагом нельзя перезаписать через консоль (отказ "is read-only").
Мы используем `FCVAR_GLCONFIG` для того чтобы вовремя пробросить значение из vk_hdr и потенциально других параметров которые нужны нам на раннем этапе. Иначе нет возможности пробросить при загрузке значение из конфига, оно просто всегда по умолчанию.
Если ты готов сейчас тратить время на изменение порядка рендера*, то можешь отказать в этом конкретном изменении и я поменяю FCVAR_GLCONFIG на FCVAR_ARCHIVE. Главное не отправлять это в долгий ящик. Это всего 1 строчка без серьёзных изменений, как временное решение более чем хорошее.
\* я пытался, но те участки что трогал либо вызываются движком слишком часто либо делаются поздно, и в целом как мне показалось они не очень семантически подходят, а когда спрашиваю куда надо Альбатрос молчит :(

2021-12-03 20:51 UTC, 0x4E69676874466F78 commented
> И примерный сценарий, как оно живёт во времени и пространстве.

Это написано с учётом #251

1. вызов `R_VkInit` (vk_core.c) где `vk_core.rtx = false`.
2. вызов `initSurface` (vk_core.c) приводит к `vk_core.rtx = true` в случае если какая-то видяха имеет поддержу rtx, иначе она так и останется `false`.
3. вызов `VK_LoadCvars` (vk_cvar.c) загружает код с кварами, у нас уже есть готовый `vk_core.rtx`, если он `false` то `vk_rtx_extension = "0"`, `vk_rtx` переводится в read-only с соответствующим пояснением и умолчанием `"0"`, если он `true` то `vk_rtx_extension = "1"`, `vk_rtx` становится доступным для записи, по умолчанию он `"1"`.
4. вызов `VK_FrameCtlInit` (vk_framectl.c) зовёт `R_BeginFrame` где у нас есть проверка `vk_core.rtx && FBitSet( vk_rtx->flags, FCVAR_CHANGED )` она выполняется раз при запуске в любом случае (как понимаю такова особенность кваров или конкретно `FCVAR_GLCONFIG`), следовательно если у нас стоит в `vk.cfg` параметр `vk_rtx "0"` то `g_frame.rtx_enabled` будет присвоено `false` иначе `true`, которое улетит уже в `VK_RenderBegin( g_frame.rtx_enabled );`.

2021-12-03 20:52 UTC, 0x4E69676874466F78 commented on ref_vk/vk_framectl.c
> +	gEngine.Cvar_Set("vk_rtx", g_frame.rtx_enabled ? "1" : "0");
Это сделано для того чтобы режим при vk_rtx_toggle запоминался в конфиг, а не слетал после перезапуска.

2021-12-05 06:02 UTC, w23 approved these changes

2021-12-05 06:02 UTC, merged