HDR output
w23/xash3d-fwgs pull request #249
Opened 2021-12-02 18:29 UTC by 0x4E69676874466F78

Только базовая поддержка. Включается через vk_hdr 1 и требуется перезапуск для вступления в силу. 
Работает как с лучами так и без, но HDR не отнормирован. Не рекомендуется запускать на OLED, так как интерфейс может выжечь матрицу.
Для изменения в реальном времени не хватает корректного пересоздание рендерпасса.

2021-12-02 18:39 UTC, w23 requested changes

2021-12-02 18:39 UTC, w23 commented on ref_vk/vk_framectl.c
> +	qboolean hdr_output = CVAR_TO_BOOL( vk_hdr );
вот поэтому сломалась

2021-12-02 19:03 UTC, 0x4E69676874466F78 commented on ref_vk/vk_framectl.c
> +	qboolean hdr_output = CVAR_TO_BOOL( vk_hdr );
Спасибо, глаз замылился.

2021-12-02 19:05 UTC, 0x4E69676874466F78 commented on ref_vk/vk_framectl.c
> +	qboolean hdr_output = CVAR_TO_BOOL( vk_hdr );
Хотя постой.

2021-12-02 19:21 UTC, w23 commented on ref_vk/vk_framectl.c
> +	qboolean hdr_output = CVAR_TO_BOOL( vk_hdr );
https://github.com/w23/xash3d-fwgs/runs/4399230924?check_suite_focus=true#step:5:1264

Надо чтобы декларация была до `PROFILER_SCOPES`. Спасибо C89 за наше счастливое детство.

2021-12-02 19:22 UTC, 0x4E69676874466F78 commented on ref_vk/vk_framectl.c
> +	qboolean hdr_output = CVAR_TO_BOOL( vk_hdr );
Какой же там неудобный лог эх.
> ../ref_vk/vk_framectl.c:216:2: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
Что я должен для C90 сделать?

2021-12-02 19:29 UTC, 0x4E69676874466F78 commented on ref_vk/vk_framectl.c
> +	qboolean hdr_output = CVAR_TO_BOOL( vk_hdr );
Понял.

2021-12-02 19:50 UTC, 0x4E69676874466F78 commented
Известная проблема: падает если нет нужного пространства при `vk_hdr 1`, попробую добавить обход.

2022-01-22 22:20 UTC, 0x4E69676874466F78 commented
На данный момент пуллреквест сломан. Последний рабочий коммит 354a525

2022-01-23 00:11 UTC, 0x4E69676874466F78 commented
Исправил.

2022-01-23 00:17 UTC, 0x4E69676874466F78 commented
https://github.com/NVIDIA/Q2RTX/pull/159/files здесь есть код для скриншотов и для вычисления nit. 
При этом с цветовыми пространствами для HDR там странно, завтра гляну как оно у них в игре работает.

2022-01-24 00:15 UTC, 0x4E69676874466F78 commented
Похоже преимущество VK_FORMAT_R16G16B16A16_SFLOAT + VK_COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT над VK_FORMAT_A2B10G10R10_UNORM_PACK32 + VK_COLOR_SPACE_HDR10_ST2084_EXT это что не надо делать гамма-коррекцию в конце. Но VK_FORMAT_A2B10G10R10_UNORM_PACK32 кажется оптимальнее потому что надо гонять 30 бит вместо 48. https://ourmachinery.com/post/supporting-native-hdr-monitors/

2023-12-09 00:13 UTC, ils8 commented on ref_vk/shaders/brush.frag
> +		//baseColor.rgb = OECF_sRGB(aces_tonemap(baseColor.rgb));
! lolol

2023-12-13 17:40 UTC, 0x4E69676874466F78 commented on ref_vk/shaders/brush.frag
> +		//baseColor.rgb = OECF_sRGB(aces_tonemap(baseColor.rgb));
Понятия не имею что ты тут хотел сказать.

2024-01-11 14:39 UTC, 0x4E69676874466F78 commented
Закрыто в пользу https://github.com/w23/xash3d-fwgs/pull/727

2024-01-11 14:39 UTC, closed without merging