Sync with upstream, small fixes for wscript, print all unsupported extensions
w23/xash3d-fwgs pull request #272
Opened 2021-12-09 22:31 UTC by a1batross

$subj

An important note:
Under non-Windows platforms installation process has been made A LOT easier. You don't need to specify `-W --prefix=''`, just add `--destdir` during install phase and it should be fine.

Unfortunately, there is a problem with Waf which doesn't allow this on Windows.

2021-12-10 00:33 UTC, 0x4E69676874466F78 commented
Спасибо за `conf.env.CFLAGS.remove('-Werror=declaration-after-statement')`.
А почему решил убрать запрет сборки вулкана на андроиде? оно же не работает.

2021-12-10 03:08 UTC, a1batross commented
@0x4E69676874466F78 лучше видеть ошибку чем затыкать дырку.

Тем более когда она сделана настолько криво. Почему так -- я пояснил в коммите. Во-первых, макрос нарушает целостность интерфейсов. Во-вторых, он не имеет никакого смысла. Платформы где Vulkan невозможен уж лучше воткнут стабы внутрь этих интерфейсов, чем потенциально будут ломать совместимость. Это значит что платформо-зависимый код нужно доделывать, но этим скорее всего займусь я.

Тем более цель форка -- это всё-таки ref_vk. Как-то странно оставлять сборку под Android, когда заранее известно что она сломана. Если мешает -- лучше закомментировать в GitHub Actions.

2021-12-10 04:45 UTC, w23 requested changes
Ох ничего себе, к нам PR с апстрима!
Спасибо!

А можно Андроид сразу в составе этой штуки правильно закомментить из GHA? Ну чтобы я коммитил _ЗЕЛЁНЕНЬКОЕ_ :green_heart:.

2021-12-10 12:06 UTC, a1batross commented
Задизейблил Android

2021-12-11 01:49 UTC, w23 approved these changes

2021-12-11 01:50 UTC, merged