new flashlight (beta)
w23/xash3d-fwgs pull request #315
Opened 2021-12-24 21:51 UTC by 0x4E69676874466F78

Сейчас фонарик смещён вверх, смотрится это более-менее. 
Яркость компромиссная, если сделать 250 уже пересвечивает оружие.
Подогнал пока фонарик ближе к оригиналу. Свою задачу в игре выполняет нормально.
При vk_rtx_freeze будет постоянно аллоцироваться источник, это можно обойти если всё же сделать аллокацию в cl_tent.c, но с пустыми значениями кроме dl->die, я сначала до этого не додумался, но пока предварительная версия без этого (завтра поэкспериментирую).

И я не понимаю как сместить фонарик в сторону, чтобы он был на плече и смотрел наискосок (ориентирован в центр экрана), при этом не ломался на поворотах. Это нужно что-то сделать со значениями из g_camera->vforward обработав их относительно нового origin или же получить свой vforward относительно этого нового origin. А я ![:weakling:](https://cdn.discordapp.com/emojis/804498549282045983.png?size=24)

Скриншоты:
![изображение](https://user-images.githubusercontent.com/4449851/147372790-a36c9186-6283-473e-80a2-0bc3cd25cdac.png)
В вентиляции не идеально, но работает:
![изображение](https://user-images.githubusercontent.com/4449851/147372851-85957702-0fb7-4f75-b268-11dcd6c19a9b.png)

2021-12-26 13:25 UTC, EliteCombineSoldier commented
adding delay to the flashlight movement like how black mesa does it would be cool

2021-12-26 14:04 UTC, 0x4E69676874466F78 commented
@EliteCombineSoldier да, возможно было бы неплохо, но это уже выше моих возможностей, ну или я уже устал заниматься фонариком.
Изначально фонарик немного пошатывался при ходьбе, но это пришлось убрать потому что при сетевой игре говорят будут проблемы если брать данные от энтити игрока.

2021-12-27 07:50 UTC, w23 requested changes

2021-12-27 07:50 UTC, w23 commented on ref_vk/vk_rmain.c
> +		return true;
А тут можно вернуть, есть у нас ртх или нет, и тогда не придётся городить грязь в vk_render

2021-12-27 07:50 UTC, w23 commented on ref_vk/vk_light.c
> +	}
Это не выглядит как правильная логика. Если вдруг у нас длайтов много (даже не имеющих отношение к фонарю), то на каждый будет создаваться свой фонарик.

Нужно ровно один раз проверить, стоит ли на игроке эффект (но я пока не понимаю, что это за эффект, и почему оно так работает), и тогда добавить, вне функци `addDlight`. Например, в `VK_LightsFrameFinalize`.

2021-12-27 07:50 UTC, w23 commented on ref_vk/vk_light.c
> +	*plight = (vk_point_light_t){0};
Нет необходимости делать это тут руками (к тому же, например, потерялась проверка на переполнение).

Лучше готовь фиктивную `vk_light_entity_t` и зови `addSpotLight`. Оно там всё сделает уже, как надо.

2021-12-27 07:50 UTC, w23 commented on ref_vk/vk_light.c
> +			plight->dir[1] *= cosf(angle);
Я вообще не понимаю с ходу, что тут происходит, но в целом вот эти штуки с angles меня очень пугают. Их в принципе не должно быть, я не понимаю, откуда они возникли.

Должно быть как-то примерно так (псевдокод):
```
vec3 origin = ent->origin;
vec3 target = EV_VisTraceLine(camera.origin, camera.forward);
light->origin = origin;
light->dir = normalize(target - origin);
```
И всё. И никаких углов вообще.

Альтернативно, у `cl_entity_t` есть `angles`:
```
light->origin = ent->origin;
VectorAngles(ent->angles, light->dir, NULL, NULL);
```
Даже трассировать ничего не надо. Но я не знаю, насколько там лежит то, что нам нужно.

2021-12-27 07:50 UTC, w23 commented on ref_vk/vk_light.c
> +	}
Вся эта секция очень похожа на thirdperson (не смотрел внимательно), скорее всего к ней те же самые рассуждения применимы.

2021-12-27 07:50 UTC, w23 commented on engine/client/cl_tent.c
> +			dl->die = cl.time + 0.01f; // die on next frame
Можно не создавать никакой длайт, если мы руками будем по ентитям пробегаться в поисках `EF_DIMLIGHT`.

2021-12-27 12:12 UTC, 0x4E69676874466F78 commented on ref_vk/vk_rmain.c
> +		return true;
А ты будешь переделывать шейдер поинтлайта для фонарика? или может там как-то нормальный спотлайт для классического рендера сделаешь? Потому что в грязи есть смещение от стены чтобы поинтлайт выглядил правильно.
А так конечно можно, но сначала на эти вопросы ответь.

2021-12-27 12:14 UTC, 0x4E69676874466F78 commented on ref_vk/vk_light.c
> +	}
> Если вдруг у нас длайтов много (даже не имеющих отношение к фонарю), то на каждый будет создаваться свой фонарик.

Не будет. Откуда ты взял что будет? Мы проверяем есть ли у игрока длайт с EF_DIMLIGHT и больше ни у кого.
Но вообще я щас поменяю тут немного логику чтобы не делать эту проверку всё время а только если к нам прилетел длайт с отрицательным радиусом.

2021-12-27 12:16 UTC, 0x4E69676874466F78 commented on ref_vk/vk_light.c
> +	*plight = (vk_point_light_t){0};
Это было так сделано когда я хотел отказаться от передачи длайта, был конфликт типов, а потом забыл. Сейчас переделаю.

2021-12-27 12:18 UTC, 0x4E69676874466F78 commented on engine/client/cl_tent.c
> +			dl->die = cl.time + 0.01f; // die on next frame
Длайт я делаю для dl->die чтобы не было вылета при vk_rtx_frezee и чтобы не творить рефакторинг. 

И уже писал, нам не надо пробегаться по энтитям, мы берём конкретно энтити игрока.

2021-12-27 12:30 UTC, 0x4E69676874466F78 commented on ref_vk/vk_light.c
> +			plight->dir[1] *= cosf(angle);
Происходит примерно что происходит в cl_tent.c CL_UpdateFlashlight с поправкой на нашу реальность со спотлайтом.

Оно там не в тех углах который ожидает свет, поэтому я скопипастил преобразрование которое делается для энтити с карты.

Я попробую твой псевдокод, но если не получится дальше ты сам там переделывай как надо.

2021-12-27 15:27 UTC, 0x4E69676874466F78 commented on ref_vk/vk_light.c
> +	}
Перенёс в VK_LightsFrameFinalize

2021-12-27 15:36 UTC, 0x4E69676874466F78 commented on ref_vk/vk_light.c
> +	*plight = (vk_point_light_t){0};
addSpotLight требует vk_light_entity_t то есть ему нужно то что прилетает в dlight.
Ты предлагаешь мне переделать грязный addSpotLight?
addPointLight не требует этого поэтому я взял за основу код из него.

2021-12-27 15:44 UTC, 0x4E69676874466F78 commented on ref_vk/vk_light.c
> +			plight->dir[1] *= cosf(angle);
Ты пропустил thirdperson_offset.

2021-12-27 15:45 UTC, 0x4E69676874466F78 commented on ref_vk/vk_light.c
> +			plight->dir[1] *= cosf(angle);
Я располагаю спотлайт с некоторым сдвигом от модели в 3 лице.

2021-12-27 15:59 UTC, 0x4E69676874466F78 commented on ref_vk/vk_light.c
> +			plight->dir[1] *= cosf(angle);
`AngleVectors(ent->angles, plight->dir, NULL, NULL);`
Может подойти для non-local player case но не для local player case

2021-12-27 16:18 UTC, 0x4E69676874466F78 commented on ref_vk/vk_light.c
> +			plight->dir[1] *= cosf(angle);
normalize это VectorNormalize? 
Ещё я не очень понимаю что ты тут хочешь сделать с камерой. 
Моя задача была отодвинуть от энтити с учётом высоты фонарик, иначе фонарик светит прям на саму модель. У меня это не совсем идеально сделано, но работает довольно неплохо.
К сожалению после `VectorAngles( forward, angles );` углы в формате карты энтити.
Хотя сейчас понял что если я angles дальше помещу в AngleVectors то оно делает почти что надо только верх-низ перепутан местами.

2021-12-27 16:27 UTC, 0x4E69676874466F78 commented on ref_vk/vk_light.c
> +			plight->dir[1] *= cosf(angle);
Убрал эти углы.

2021-12-27 20:18 UTC, w23 commented on engine/client/cl_tent.c
> +			dl->die = cl.time + 0.01f; // die on next frame
Если `PARM_MODERNFLASHLIGHT` только для rtx включается, то не надо ничего костылить :).

2021-12-27 20:21 UTC, w23 commented on ref_vk/vk_light.c
> +	*plight = (vk_point_light_t){0};
Не надо переделывать `addSpotLight`. Можно же просто вот так сделать:
```
{
  vk_light_entity_t le = {
    .origin = ...,
    .dir = ...,
    .color = ...,
    .radius = ...,
    // ... stopdot, etc
  };

  addSpotLight(&le, ...);
}
```

2021-12-27 22:00 UTC, 0x4E69676874466F78 commented on ref_vk/vk_rmain.c
> +		return true;
Убрал костыль для классического рендера.

2021-12-27 23:03 UTC, 0x4E69676874466F78 commented
Обратил внимание что делаю `entPlayer = gEngine.GetLocalPlayer();` и вспомнил про сеть.
Проверил и да, по сети не работает.

2021-12-27 23:31 UTC, 0x4E69676874466F78 commented
Сделал костыль, но это тот самый кривой фонарик.
Чтобы у других игроков был тоже правильные нужно:
Либо пробегаться по всему списку энититей в поиске игроков.
Либо вызывать из cl_tent.c функцию рендера которому передавать ent.
Второй вариант более предпочтительный но как это сделать пока не пойму.

2021-12-28 10:25 UTC, 0x4E69676874466F78 commented
Нашёл обходной путь.

2021-12-28 12:10 UTC, 0x4E69676874466F78 commented
Короче я починил логику с сетевой игрой, фонарики у них теперь правильные.
Однако я не знаю что делать с углами верх-вниз, они работают в пол силы, а если я домножаю то фонарик искажает.
Эту проблему я уже не могу решить самостоятельно.

2021-12-28 17:42 UTC, 0x4E69676874466F78 commented
Забыл написать что решил проблему.

2021-12-29 00:30 UTC, 0x4E69676874466F78 commented
Там MaxG3D более удачные значения для позиции камеры притащил, я их добавлю немного позже сюда.

2021-12-29 09:23 UTC, 0x4E69676874466F78 commented
Можно мержить, остальное уже другими пуллреквестами.

2021-12-30 03:31 UTC, w23 commented
Я слышал вы любите пулл-реквсеты, поэтому я выставил пулл-реквест на ваш пулл-реквест: https://github.com/0x4E69676874466F78/xash3d-fwgs/pull/3

Посмотри, пожалуйста, что я там ничего не сломал. Вмержишь себе, и я вмержу сюда.

2021-12-30 10:30 UTC, 0x4E69676874466F78 commented
Ничего не сломал. Проверил сеть, от 3 лица.

2021-12-30 17:02 UTC, merged