Sync with upstream
w23/xash3d-fwgs pull request #525
Opened 2023-04-28 14:57 UTC by a1batross

* Adds PSVita port (probably unuseful for Vulkan fork)
* There is now `-minidump` on Win32 thanks to @SNMetamorph
* Removed unsafe string functions: va(), Q_strcpy(), Q_sprintf(). Removed unused functions from libpublic (feel free to restore them!). 
* Faster COM_HashKey
* Faster R_LightLambert (used extensively with entity lights, probably irrelevant in RTX mode)
* Enabled nswitch builds back, as the culprit was in HLSDK. We now build it with `--disable-werror`.
* Waf doesn't need `--prefix` key on Windows anymore and always installs to `--destdir` directory.
* Engine fixes, multiplayer fixes, UB fixes, unit tests, etc...

2023-04-28 16:31 UTC, w23 requested changes
CI is broken ;_;

2023-04-28 19:47 UTC, w23 commented
Ага, теперь видно что `vk_studio.c` с патчами каюкнулась.

2023-05-01 04:20 UTC, w23 commented on ref/vk/vk_studio.c
> +		r = DotProduct( normal, light[i] );
Тут в диффе знак поменялся. Но я не уверен, что мы этот код вообще тестировали, и что он до этого был правильный.

2023-05-01 04:45 UTC, w23 approved these changes

2023-05-01 04:46 UTC, merged

2023-05-01 14:07 UTC, a1batross commented
Да, я не заметил этот момент. Его надо поменять обратно.

Там именно что минус должен идти для всех моделей, и без минуса для
отзеркаленных.

пн, 1 мая 2023 г., 07:20 Ivan Avdeev ***@***.***>:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In ref/vk/vk_studio.c
> <https://github.com/w23/xash3d-fwgs/pull/525#discussion_r1181381838>:
>
> > -		/* FIXME VK NOT IMPL if( tr.fFlipViewModel )
> -			r = DotProduct( normal, light[i] );
> -		else */ r = -DotProduct( normal, light[i] );
> +		r = DotProduct( normal, light[i] );
>
> Тут в диффе знак поменялся. Но я не уверен, что мы этот код вообще
> тестировали, и что он до этого был правильный.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/w23/xash3d-fwgs/pull/525#pullrequestreview-1407333896>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAYQTAPTMCAC7KSC3KOHAOLXD422XANCNFSM6AAAAAAXPLE3GQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>