vk: profiler: fix source locations for scopes (#542)
w23/xash3d-fwgs pull request #567
Opened 2023-09-16 11:27 UTC by nilsoncore

Fix source locations for scopes in `r_speeds_list_metrics` as described in Issue #542. 
Also slightly simplify metrics list print formatting and add an option to print it as a table. It can be turned on/off via cvar `r_speeds_metrics_as_table`. 
This does not look very good in HL itself because it uses non-monospace font by default in console, but it looks much cleaner and readable in console and log file output.

2023-09-16 11:38 UTC, nilsoncore commented
Here is how table printing looks:

1. HL console default print:

![xash_list_metrics_hl](https://github.com/w23/xash3d-fwgs/assets/65307695/80acca35-042d-4586-99fe-4832084091d2)

2. Host console/log default print:

![xash_list_metrics_console](https://github.com/w23/xash3d-fwgs/assets/65307695/f79b9ce7-4ee8-44fd-bf09-f7e61934427b)

3. HL console table print:

![xash_list_metrics_table_hl](https://github.com/w23/xash3d-fwgs/assets/65307695/b1987c29-5925-4a01-9257-aa07adf799bb)

4. Host console/log table print:

![xash_list_metrics_table_console](https://github.com/w23/xash3d-fwgs/assets/65307695/a13ce7cd-ec8b-491a-8400-1489ad1593ba)

P.S. - I know, it's a bit silly to make pointless "features" like this, but I think it can help a little either way, and it's just my baby steps in this huge repo, so don't judge :)

2023-09-16 12:07 UTC, 0x4E69676874466F78 commented
Последнюю строку с чёрточками можно убрать она зазря сжирает вертикальное место впользу настоящей строки, либо снизу тоже должны писать заголовки.

2023-09-16 12:28 UTC, nilsoncore commented
Кстати, неплохая идея, мне нравится. Это конечно все вкусовщина, но мне кажется заголовки снизу все же несут пользу - консоль же всегда вниз проскраливается, и чтобы посмотреть заголовки нужно будет скроллить в самое начало. Могу показать как это выглядит:

1. Консоль HL:

![xash_list_metrics_table_below_hl](https://github.com/w23/xash3d-fwgs/assets/65307695/443ce66c-eca2-4dcf-964e-298cdf4796ee)

2. Консоль хоста:

![xash_list_metrics_table_below_console](https://github.com/w23/xash3d-fwgs/assets/65307695/10d1a9bc-40b4-482a-bf86-2925a6a3b252)

2023-09-16 13:20 UTC, w23 commented
Класс! Спасибо!
Убрать бы ещё полного пути `C:\Users\Nilson\...` префикс из имён файлов, вообще было бы хорошо.
Почему: это лишняя информация и захламляет вывод. Важно только имя файла, без пути.

2023-09-16 13:29 UTC, w23 commented
- Насколько трудно сделать автоподстраивающуюся ширину колонок у таблицы?
- Что думаешь на счёт заменить квар таблицы на отдельную команду, например `r_speeds_list_metrics_table`?
- (Может, вообще укоротить команду до `r_speeds_list` и `r_speeds_listt`?)

2023-09-16 13:48 UTC, nilsoncore commented
- Автоподстроение: уже когда писал, уже сразу подумал, но не стал оверинженерить, просто хотел простенький коммит сделать для первого раза. Думаю, было бы неплохо, а с таким функционалом можно и как-то это все обобщить и в целом любые таблицы строить. Может быть за один день и не сделаю, но думаю вполне возможно.
- Отдельная команда: тоже об этом думал, но не хотелось для одной задачи делать две почти одинаковые функций. Думал над тем, чтобы сделать это параметром функции, но это надо будет указывать каждый раз, и к тому же у этой функции уже есть опциональный параметр фильтрации скопов, как-то громоздко будет несколько опциональных параметров передавать чтоли.
- Сокращение команды: честно говоря, не очень люблю, когда прям сильно укрощают, что даже значащие слова начинают пропадать. Сократить то конечно можно, но как мне кажется читабельность ухудшится, так как сразу не поймешь что команда делает по одному названию, пока не разберешься, да и для новых разработчиков будет больше работы разбираться кто что делает. Но это уже так, философия пошла.
- Убрать полный путь: это действительно хорошо, лишняя трата места и ресурсов на вывод. Вопрос только до куда убирать - с названием папки проекта (к примеру, "xash3d_fwgs"), или вовсе не включать, сразу начиная с корня/папок модулей.

2023-09-16 13:51 UTC, nilsoncore commented
Немного офф-топа: я с сожалением для себя узнал, что RTX мне не светит :(  (нет расширения ray_query, карточка 1080 Ti). Я почему-то думал, что тут как-то Path Traycing`ом обойдется, но да ладно) Постараюсь пилить вспомогательные утилиты, чтобы ты меньше времени уделял на сторонние вещи, и больше на сам рендер. (надеюсь, хах)

2023-09-16 13:57 UTC, nilsoncore commented
Так, мысли свои изложил, а к общему знаменателю не пришел. Я думаю стоит сделать так:
- Сделать автоподстроение ширины таблицы с дальнейшей возможностью обобщения всего этого и возможно выделения в небольшую общую утилиту;
- Убрать повторения, либо реструктурировать вид так, чтобы они были показаны только один раз.

Думаю эти вещи определнно стоит сделать в первую очередь. После этого тогда, скорее всего, и можно будет мержить.
Естественно команду можно переделать, убрать квар и т.д., думаю тут коллективным мнением нужно решить.

2023-09-16 14:05 UTC, w23 commented
> * Автоподстроение: уже когда писал, уже сразу подумал, но не стал оверинженерить, просто хотел простенький коммит сделать для первого раза. Думаю, было бы неплохо, а с таким функционалом можно и как-то это все обобщить и в целом любые таблицы строить. Может быть за один день и не сделаю, но думаю вполне возможно.

Не, можно не заморачиваться. Я спросил потому что вдруг есть какие-то быстрые идеи.


> * Отдельная команда: тоже об этом думал, но не хотелось для одной задачи делать две почти одинаковые функций. Думал над тем, чтобы сделать это параметром функции, но это надо будет указывать каждый раз, и к тому же у этой функции уже есть опциональный параметр фильтрации скопов, как-то громоздко будет несколько опциональных параметров передавать чтоли.

Сишная функция печати может быть ровно одна такая же, как сейчас, просто вместо квара аргументом принимать, печатать таблицей, или нет. Для регистрации команд придётся городить вспомогательные функции, но это оправдано, имо.

> * Сокращение команды: честно говоря, не очень люблю, когда прям сильно укрощают, что даже значащие слова начинают пропадать. Сократить то конечно можно, но как мне кажется читабельность ухудшится, так как сразу не поймешь что команда делает по одному названию, пока не разберешься, да и для новых разработчиков будет больше работы разбираться кто что делает. Но это уже так, философия пошла.

Дело в том, что для частого использования длинные команды очень неудобны -- всегда платишь за набор. А укорочение команд делает новичкам сложнее на 10 секунд (и то неясно).

Здесь у меня ещё промелькнула мысль на будущее, что, может, вообще позволить рулить графиками не через их полные длинные имена, а через численные индексы, которые здесь в списке и выводить. Так их вообще супер быстро и легко добавлять было бы. Это не в этот PR конечно же.

> * Убрать полный путь: это действительно хорошо, лишняя трата места и ресурсов на вывод. Вопрос только до куда убирать - с названием папки проекта (к примеру, "xash3d_fwgs"), или вовсе не включать, сразу начиная с корня/папок модулей.

Тупо имя файла без никто, с самого крайнего правого `'/'`. В этой кодобазе одного имени файла достаточно для полной идентификации.

2023-09-16 14:06 UTC, w23 commented
> Немного офф-топа: я с сожалением для себя узнал, что RTX мне не светит :( (нет расширения ray_query, карточка 1080 Ti). Я почему-то думал, что тут как-то Path Traycing`ом обойдется, но да ладно) Постараюсь пилить вспомогательные утилиты, чтобы ты меньше времени уделял на сторонние вещи, и больше на сам рендер. (надеюсь, хах)

Если у тебя есть `VK_KHR_ray_tracing_pipeline`, то не всё потеряно -- #495

2023-09-16 14:10 UTC, w23 commented
> Так, мысли свои изложил, а к общему знаменателю не пришел. Я думаю стоит сделать так:
> 
>     * Сделать автоподстроение ширины таблицы с дальнейшей возможностью обобщения всего этого и возможно выделения в небольшую общую утилиту;
> 
>     * Убрать повторения (и путей, и в принципе всего по возможности), либо реструктурировать вид так, чтобы они были показаны только один раз.
> 
> 
> Думаю эти вещи определнно стоит сделать в первую очередь. После этого тогда, скорее всего, и можно будет мержить. Естественно команду можно переделать, убрать квар и т.д., думаю тут коллективным мнением нужно решить.

Автоширина это совсем бонус, если прям делать нечего :).
Остальное должно быть быстро.

От меня только две хотелки:
- [ ] Имя файла (пути вообще не нужны, не надо заморачиваться -- находишь самый правый `/` или `\` и только хвост за ним отображаешь).
- [ ] Короткие команды

2023-09-16 14:16 UTC, 0x4E69676874466F78 commented
На тему моноширинного шрифта: https://github.com/w23/xash3d-fwgs/issues/141

2023-09-16 14:21 UTC, 0x4E69676874466F78 commented
@nilsoncore 
> нет расширения ray_query, карточка 1080 Ti

А почему тут пишет что есть:
https://vulkan.gpuinfo.org/listdevicescoverage.php?extension=VK_KHR_ray_query&platform=all
?
Альтернатива уже выше упомянутый https://vulkan.gpuinfo.org/listdevicescoverage.php?extension=VK_KHR_ray_tracing_pipeline&platform=all
Возможно в новых драйверах остался только VK_KHR_ray_tracing_pipeline, где-то что-то такое уже слышал от одного парня на стриме.

2023-09-16 14:23 UTC, nilsoncore commented
> Если у тебя есть VK_KHR_ray_tracing_pipeline, то не всё потеряно -- https://github.com/w23/xash3d-fwgs/issues/495

Сайт вулкана gpuinfo пишет, что у меня вроде как версия r.1 должна быть. Будем думать, что надежды есть.

> Имя файла (пути вообще не нужны, не надо заморачиваться -- находишь самый правый / или \ и только хвост за ним отображаешь).

Согласен, тут в принципе и так у каждого файла есть префикс, можно сильно не заморачиваться.

> Короткие команды

Суть я понимаю, да, не хочется каждый раз длинную команду писать. Вообще вроде есть алиасы? Но возможно я это путаю с сорсом уже, так что не буду говорить наверняка. Думаю можно сократить, может быть даже элегантнее имя придумаю (но это не точно). 

> На тему моноширинного шрифта: https://github.com/w23/xash3d-fwgs/issues/141

Вообще моноспейс был бы неплох, тогда в консоли что угодно можно будет выровнять. Но, будет немного больше места занимать. Вообще, конечно, оригинальный шрифт не очень приятно читать, но он как бы оригинальный, выпиливать тоже не хочется... Хотя, пока что это касается только одной таблички метрик. Если уж разрастется проблема, там можно будет смотреть.

В общем, сделаю сначала базу, которую провод попросил, а там уже дальше посмотрим.

2023-09-16 14:29 UTC, nilsoncore commented
> А почему тут пишет что есть:

Там драйвер старый, 2020 года. Там да, пишет что есть. Но когда смотрю по новому драйверу (который у меня стоит), там такого нет, но есть `VK_KHR_ray_tracing_pipeline` и `VK_NV_ray_tracing`

2023-09-16 15:42 UTC, w23 commented
> > А почему тут пишет что есть:
> 
> Там драйвер старый, 2020 года. Там да, пишет что есть. Но когда смотрю по новому драйверу (который у меня стоит), там такого нет, но есть `VK_KHR_ray_tracing_pipeline` и `VK_NV_ray_tracing`

Вот эту бы всю переписку в #495 ~изначально провести~ скинуть, потому что ну какие-то битики знания, которые тут потеряются.

2023-09-16 15:59 UTC, 0x4E69676874466F78 commented
@w23 "перенёс".

2023-09-16 16:26 UTC, 0x4E69676874466F78 commented
@nilsoncore 
> Вообще моноспейс был бы неплох, тогда в консоли что угодно можно будет выровнять. Но, будет немного больше места занимать. Вообще, конечно, оригинальный шрифт не очень приятно читать, но он как бы оригинальный, выпиливать тоже не хочется... Хотя, пока что это касается только одной таблички метрик. Если уж разрастется проблема, там можно будет смотреть.

Там этот "оригинальный" несколько раз менялся (в какой-то из WON версии он был другой, в стиме вообще третий-четвёртый). Но моноширинный визуально выглядит не очень, хорошо бы "оригинальный" перерисовать под моноширинный.

2023-09-16 16:33 UTC, w23 commented
> @nilsoncore
> 
> > Вообще моноспейс был бы неплох, тогда в консоли что угодно можно будет выровнять. Но, будет немного больше места занимать. Вообще, конечно, оригинальный шрифт не очень приятно читать, но он как бы оригинальный, выпиливать тоже не хочется... Хотя, пока что это касается только одной таблички метрик. Если уж разрастется проблема, там можно будет смотреть.
> 
> Там этот "оригинальный" несколько раз менялся (в какой-то из WON версии он был другой, в стиме вообще третий-четвёртый). Но моноширинный визуально выглядит не очень, хорошо бы "оригинальный" перерисовать под моноширинный.

Из тупых идей про выравнивание можно:
- рисовать руками по координатам на экран (неудобно смотреть из консоли)
- руками посчитать метрики шрифта для глифов и насыпать их из расчёта выравнивания под конкретные ширины в пикселях (всё равно будет плавать, сломает красивую картинку в логе)

Но вообще думаю, что табличка это факультатив, и можно не заморачиваться особо.

2023-09-17 14:34 UTC, nilsoncore commented
Сделал доработки, теперь:

- Заголовок/формат вывода дублируется в конце вывода (для удобства);
- Выводится только название файла исходника, а не весь путь;
- Единая команда `r_speeds_list_metrics` с переключением режимов через cvar `r_speeds_metrics_as_table` заменена на две укороченные в названии команды `r_speeds_mlist` и `r_speeds_mtable`.

Благодаря сокращению путей, кстати, стало заметно читабельнее, и даже в консоли HL табличка выглядит еще более менее. Думаю, этих изменений вполне достаточно и нужно двигаться дальше, так как этот вывод еще долго можно улучшать, но полезной работы от этого мало.

Как теперь это выглядит:

1. Metrics list in HL console:

![metrics_list_hl](https://github.com/w23/xash3d-fwgs/assets/65307695/70197fe7-3ed9-428c-8408-2a6c595954cc)

2. Metrics list in host console:

![metrics_list_console](https://github.com/w23/xash3d-fwgs/assets/65307695/ddf4028a-9954-468e-8555-25c80a3a958d)

3. Metrics table in HL console:

![metrics_table_hl](https://github.com/w23/xash3d-fwgs/assets/65307695/8a4e9109-d450-4cba-ad02-db984f576be9)

4. Metrics table in host console:

![metrics_table_console](https://github.com/w23/xash3d-fwgs/assets/65307695/30d33efa-6690-4e57-8eed-d2823dbce576)

5. Metrics with filters in HL console:

![metrics_filters_hl](https://github.com/w23/xash3d-fwgs/assets/65307695/1b3e2d0f-95ca-4918-bb4b-0c49fe01a4bb)

6. Metrics with filter in host console:

![metrics_filters_console](https://github.com/w23/xash3d-fwgs/assets/65307695/07d9c004-bf6b-4e74-a6a1-ffb6fac79cc8)

2023-09-17 19:57 UTC, w23 requested changes
Благодарю!
Новые названия ок.
Оставил несколько пожеланий ещё.

2023-09-17 19:57 UTC, w23 commented on ref/vk/profiler.h
> +#define APROF_FILENAME(filepath) aprof_get_filename_from_filepath( filepath, Q_strlen( filepath ) )
Давай перенесём выделение имени файла уже в функцию вывода списка в `r_speeds.c`.

Почему:
- вычленение имени нужно только в списке
- регистрация scope останется тривиальной без какой-либо логики вообще
- могу представить случай, для которого полное имя для scope всё же полезно: экспорт профиля в html с графиками, где на scope можно кликнуть и попасть напрямую в файл по его полному пути. Это может возникнуть в #59 и #487

2023-09-17 19:57 UTC, w23 commented on ref/vk/profiler.h
> +#define APROF_FILENAME(filepath) aprof_get_filename_from_filepath( filepath, Q_strlen( filepath ) )
То, что мы по строчкам будем елозить каждый раз при выводе списка, нестрашно -- это супер дешёвая операция по сравнению со всем остальным.

2023-09-17 19:57 UTC, w23 commented on ref/vk/profiler.h
> +
И это заодно спрячется в `r_speeds.c`

2023-09-17 19:57 UTC, w23 commented on ref/vk/profiler.h
> +// on Windows: C:/Users/User/xash3d-fwgs/ref/vk/vk_rtx.c  ->  vk_rtx.c
Для корректности
```suggestion
// on Windows: C:\Users\User\xash3d-fwgs\ref\vk\vk_rtx.c  ->  vk_rtx.c
```

2023-09-17 19:57 UTC, w23 commented on ref/vk/profiler.h
> +		filepath_length = Q_strlen( filepath );
Непонятно, зачем нужен `filepath_length`, если мы всё равно потом strlen делаем. Он мог бы быть нужен в случае, если бы мы:
- передавали сюда string_view и не могли бы рассчитывать на `\0` в конце строки.
- кормили эту функцию гигантскими статическими строками, и могли бы передать бесплатный `sizeof()` вторым аргументом при вызове.

2023-09-17 19:57 UTC, w23 commented on ref/vk/profiler.h
> +	return NULL;
Что будет, если вдруг `__FILE__` будет содержать ровно один символ?
(это, конечно, фантастический случай, но)

2023-09-17 19:57 UTC, w23 commented on ref/vk/r_speeds.c
> +							/* line     */ scope->source_line);
Не согласен с разворачиванием -- здесь более-менее всё читается, кроме `reset` (в таких случаях, кстати, иногда делают, например, `const qboolean reset = true;`, а потом уже передают в аргументы.

2023-09-17 19:57 UTC, w23 commented on ref/vk/r_speeds.c
> +
То же самое тут.

2023-09-17 19:57 UTC, w23 commented on ref/vk/r_speeds.c
> +static void doPrintMetrics( r_speeds_mprint_mode_t *print_mode, const char *print_filter ) {
Сомневаюсь, что передавать аргументы этой функции оправдано -- она всё равно уже работает с `static struct g_speeds`, и к `print_mode`, и к `print_filter` может ходить напрямую.

2023-09-17 19:57 UTC, w23 commented on ref/vk/r_speeds.h
> +	R_SpeedsRegisterMetric(&(var), MODULE_NAME, name, type, /*reset*/ true, #var, APROF_FILENAME( __FILE__ ), __LINE__)
Здесь тоже не нужно резать

2023-09-17 19:57 UTC, w23 commented on ref/vk/r_speeds.c
> +		line_format   = "";
Здесь бы
```suggestion
		line_format   = NULL;
```

2023-09-17 19:57 UTC, w23 commented on ref/vk/r_speeds.c
> +	gEngine.Con_Printf( line_format, line, line, line, line );
А потом тут
```suggestion
	if (line_format)
		gEngine.Con_Printf( line_format, line, line, line, line );
```

2023-09-17 19:58 UTC, w23 commented on ref/vk/r_speeds.c
> +static void handlePrintFilterArg() {
Не собирается под линью, надо так:
```suggestion
static void handlePrintFilterArg(void) {
```

2023-09-17 20:21 UTC, nilsoncore commented on ref/vk/profiler.h
> +		filepath_length = Q_strlen( filepath );
Как раз таки хотел немного оптимизировать под случай, если много строк сюда очень длинных пихать (а по сути пути не очень короткие), поэтому и guard небольшой стоит. Но если рассматривать конкретно ее применение, то используется она только в файловом скопе для конкретной цели, поэтому да, наверно можно и без этого обойтись.

2023-09-17 20:23 UTC, nilsoncore commented on ref/vk/profiler.h
> +	return NULL;
И как, будем этот фантастический случай учитывать?) Наверно все же да, не хочется свалиться в рандомном местеЮ стабильность превыше всего. Как уже было выше, метрик не очень много и операция быстрая, поэтому исправлю.

2023-09-17 20:24 UTC, nilsoncore commented on ref/vk/r_speeds.c
> +							/* line     */ scope->source_line);
Эх, ну ладно. Принято, ревертну

2023-09-17 20:27 UTC, nilsoncore commented on ref/vk/r_speeds.c
> +static void doPrintMetrics( r_speeds_mprint_mode_t *print_mode, const char *print_filter ) {
Та же тема, что и с сокращением путей - лишняя открытость функции. Если уж они статические, то действительно наверно не стоит их так сильно обощать, выводить аргументы. Не опытен еще, но зато теперь буду знать и учитывать.

2023-09-17 20:29 UTC, nilsoncore commented on ref/vk/r_speeds.c
> +	gEngine.Con_Printf( line_format, line, line, line, line );
Это выглядит более читабельно, и функция лишний раз не вызывается. Пока морочился с форматами, даже как-то и не подумал об этом. Поправлю.

2023-09-17 20:32 UTC, nilsoncore commented
Спасибо за такое развернутое ревью!
Все комментарии прочитал, уже приступаю к исправлению.

2023-09-17 20:54 UTC, nilsoncore commented on ref/vk/r_speeds.c
> +	gEngine.Con_Printf( line_format, line, line, line, line );
А, я кажется вспомнил почему я так сделал. Я как раз таки не хотел два `if`'а ставить, и поэтому оставил пустую строку, которую вывод вроде как не должен обрабатывать. Стоит ли переделать, или оставить так?

2023-09-17 22:50 UTC, nilsoncore commented
Все поправил, должно быть готово для мержа.

2023-09-17 23:21 UTC, w23 requested changes
Чуток ещё комментариев и да.

2023-09-17 23:21 UTC, w23 commented on ref/vk/profiler.h
> +
Более не нужно.
```suggestion
```

2023-09-17 23:21 UTC, w23 commented on ref/vk/r_speeds.c
> +	return NULL;
Если ему дали односимвольного чувака, пусть он его самого и вернёт:
```suggestion
	return filepath;
```

2023-09-17 23:21 UTC, w23 commented on ref/vk/r_speeds.c
> +	int cursor = length - 1;
```suggestion
	int cursor = Q_strlen( filepath ) - 1;
```
см ниже почему так можно

2023-09-17 23:21 UTC, w23 commented on ref/vk/r_speeds.c
> +			return &filepath[cursor];
`cursor` всегда строго меньше длины, т.к `cursor = lenth - 1`.
```suggestion
			return &filepath[cursor+1];
```

2023-09-17 23:21 UTC, w23 commented on ref/vk/r_speeds.c
> +		memset( line, '-', sizeof( line ) );
Нуль-терминировать бы её, чтобы не устроить _хлопок_, если в `line_format` приедет ширина больше 63 в некотором будущем, когда все уже забудут, что тут происходит.
```suggestion
		memset( line, '-', sizeof( line ) );
		line[sizeof(line)-1] = '\0';
```

Вообще, я бы эту линию как-то по-другому рисовал, но хороших идей кроме того, что тупо руками эту строчку сделать статичной константой (ширины всё равно фиксированы), нет, пока пусть будет так.

2023-09-18 00:00 UTC, nilsoncore commented
> Нуль-терминировать бы её, чтобы не устроить _хлопок_, если в `line_format` приедет ширина больше 63 в некотором будущем, когда все уже забудут, что тут происходит.

Как раз для этого проставил в формате вывода строк ограничение на кол-во выводимых символов, но согласен, в любом случае нужно затерминировать.

Поправил.

2023-09-18 01:37 UTC, w23 requested changes

2023-09-18 01:37 UTC, w23 commented on ref/vk/r_speeds.c
> +		// which can toggle this printing method on/off.
Лол я пропустил этот коммент, сорян. Надо либо убрать, либо поправить на новые команды.

(этот пулл-реквест теперь выглядит _профессионально™_)

2023-09-18 02:54 UTC, nilsoncore commented on ref/vk/r_speeds.c
> +		// which can toggle this printing method on/off.
Косяк то все равно мой, хорошо что заметил! У тебя прям глаз-алмаз ахахах
Да уж, столько напропускал... Честно говоря код база такая большая, что я очень быстро теряюсь, потому что приходится прыгать туда-сюда. Надеюсь, с опытом будет попроще.

2023-09-18 03:05 UTC, nilsoncore commented
Поправил. Молюсь на мерж...

2023-09-18 03:13 UTC, w23 approved these changes
Ща CI пройдёт и вмержу

2023-09-18 03:18 UTC, nilsoncore commented
Это реально?! xD

2023-09-18 03:20 UTC, merged