Фикс аллокаций текстур-заглушек
w23/xash3d-fwgs pull request #600
Opened 2023-10-11 00:27 UTC by zgdump

Это бэкпорт моего фикса для оригинального Xash3D-FWGS, сделанного в незаконченном менеджере текстур.

Чинит #532.

2023-10-11 00:28 UTC, zgdump commented
Не то, чтобы какой-то важный фикс, но раз увидел ишью и могу поправить за минуту, почему бы это и не сделать)

2023-10-12 13:28 UTC, w23 requested changes
Правильно ли я понимаю, что ему просто не хватало места в статичном буфере?

2023-10-12 13:28 UTC, w23 commented on ref/vk/vk_textures.h
> +#define BLUE_NOISE_TEXTURE_ID 7
Надо ещё в шейдерах обновить референс тогда.

2023-10-12 13:28 UTC, w23 commented on ref/vk/vk_textures.c
> +	tglob.mempool = Mem_AllocPool( "vktextures" );
А зачем mempool?
А где он удаляется?

2023-10-12 13:28 UTC, w23 commented on ref/vk/vk_textures.c
> +	r_image->buffer  = Mem_Malloc( tglob.mempool, r_image->size);
А где мы освобождаем этих парней?

2023-10-12 14:00 UTC, zgdump commented
@w23 

> Правильно ли я понимаю, что ему просто не хватало места в статичном буфере?

Именно так. И по итогу указанный размер буфера и фактический просто не сходились.

Ещё я видел проблему в том, что берётся указатель на статический буффер. Если кто-то бы дёрнул дефолтную текстуру по её номеру, он бы просто получил мусор, ибо этот же буффер используется и для других текстур.

2023-10-12 14:01 UTC, zgdump commented on ref/vk/vk_textures.h
> +#define BLUE_NOISE_TEXTURE_ID 7
Я думал, у тебя как-то этот define шарится O_o
Где обновить?

2023-10-12 14:02 UTC, zgdump commented on ref/vk/vk_textures.c
> +	r_image->buffer  = Mem_Malloc( tglob.mempool, r_image->size);
Нигде. Дефолтные текстуры живут столько же, сколько и рендер.

2023-10-12 14:03 UTC, zgdump commented on ref/vk/vk_textures.c
> +	tglob.mempool = Mem_AllocPool( "vktextures" );
Аллокации в Ксаше должны делаться через пул. Так сделано везде и я не стал отступать от этого. Освобождать пул не нужно, ибо он используется только для дефолтных текстур, которые живут столько же, сколько и сам рендер.

2023-10-12 21:21 UTC, w23 commented on ref/vk/vk_textures.c
> +	r_image->buffer  = Mem_Malloc( tglob.mempool, r_image->size);
Я бы их `TODO`хами полил, чтобы было понятно, что они текут.

2023-10-12 21:22 UTC, w23 commented on ref/vk/vk_textures.c
> +	tglob.mempool = Mem_AllocPool( "vktextures" );
Я рано или поздно захочу сделать graceful деструкцию рендера, чтобы он чистил за собой при ошибках инициализации (ну или для переключения рендеров на лету), поэтому было бы хорошо понимать, что где течёт.

2023-10-12 21:23 UTC, w23 commented on ref/vk/vk_textures.h
> +#define BLUE_NOISE_TEXTURE_ID 7
Не, он в таком месте, что шарить неприятно.
Обновлять тут: https://github.com/w23/xash3d-fwgs/blob/726fcee3f79bc91fa0f4eb28a561502ba17f9278/ref/vk/shaders/bluenoise.glsl#L11

2023-10-12 21:24 UTC, w23 commented
Сорян за конфликт, жизнь-боль

2023-10-13 17:43 UTC, zgdump commented on ref/vk/vk_textures.c
> +	tglob.mempool = Mem_AllocPool( "vktextures" );
С удовольствием насыплю тебе ещё тудух!

2023-10-13 17:48 UTC, zgdump commented
> Сорян за конфликт, жизнь-боль

Сейчас бы в Сибирь, а не решать конфликты :(

Ребейзнул, поправил всё, что попросил.

2023-10-14 02:49 UTC, w23 commented
> Ещё я видел проблему в том, что берётся указатель на статический буффер. Если кто-то бы дёрнул дефолтную текстуру по её номеру, он бы просто получил мусор, ибо этот же буффер используется и для других текстур.

Этот буфер используется одноразово. После того, как он загружается в вулкан, он больше не нужен. Поэтому статика абсолютно уместна, с точностью до размера.

2023-10-14 03:23 UTC, w23 approved these changes

2023-10-14 03:24 UTC, merged