Denoise diffuse indirect lighting
w23/xash3d-fwgs pull request #750
Opened 2024-12-17 21:26 UTC by LifeKILLED

For enabling new denoising method use cvars:

rt_denoise_gi_by_sh 1
Enable denoising global illumination by Quake 2 algorythm (spherical harmonics)

rt_only_diffuse_gi 1
Blend diffuse and specular indirect lighting for cleaner image (reflections denoising will be in future with other algorythm)

2024-12-17 22:18 UTC, LifeKILLED commented
New denoising (my):
![image](https://github.com/user-attachments/assets/1e217771-a58a-4de3-a523-6cbfdef8fac8)

Old denoising (in "vulkan" branch now):
![image](https://github.com/user-attachments/assets/2921828d-f9bc-452a-8ac7-42ca097c18ac)

Without global illumination:
![image](https://github.com/user-attachments/assets/597ef2f0-0d9c-4fc4-b743-17ef7ee7d17f)

2024-12-18 15:17 UTC, w23 requested changes
Кодировка слетела в двух местах.
А ещё мне не очень понятно, как именно вкл/выкл флагами делается -- в `denoiser.comp` изменения не под флагами.

2024-12-18 15:17 UTC, w23 commented on ref/vk/shaders/denoiser.comp
> +// Adding emissive_blend to the final color in the *incorrect* sRGB-? space. It makes
то же самое

(editorconfig там форсит latin1, я не вмержил исправление в эту ветку ещё)

2024-12-18 15:17 UTC, w23 commented on ref/vk/shaders/denoiser.comp
> -				c.direct_diffuse += imageLoad(light_poly_diffuse, p).rgb * direct_diffuse_scale;
Это нормально, что это изменение не под флагом?

2024-12-18 15:17 UTC, w23 commented on ref/vk/shaders/denoiser.comp
> +	vec3 diffuse = c.direct_diffuse + c.indirect_diffuse + indirect_diffuse_sh;
тоже не под флагом, как оно работает?

2024-12-18 15:17 UTC, w23 commented on ref/vk/shaders/denoiser.comp
> +	c.indirect_diffuse += imageLoad(indirect_diffuse_denoised_by_sh, p).rgb;
не под флагом

2024-12-18 17:12 UTC, LifeKILLED commented on ref/vk/shaders/denoiser.comp
> +// Adding emissive_blend to the final color in the *incorrect* sRGB-? space. It makes
Не знаю, что делать с кодировкой :( Она ломается в любом случае. Надо как-то настраивать IDE, чтобы такого не было, но я пока не знаю, как

2024-12-18 17:13 UTC, LifeKILLED commented on ref/vk/shaders/denoiser.comp
> +	// TODO(or not todo): The �-Trous paper mentions that it should be c2 + d1 + d0, but
Я пробовал заменять символ обратно, но видимо IDE само сменило кодировку под Виндой, не знаю, что делать :( Из-за этого пишу все на английском всегда

2024-12-18 17:13 UTC, LifeKILLED commented on ref/vk/shaders/denoiser.comp
> -				c.direct_diffuse += imageLoad(light_poly_diffuse, p).rgb * direct_diffuse_scale;
Это ошибка, я удалил лишнюю строку, исправлю

2024-12-18 17:19 UTC, LifeKILLED commented on ref/vk/shaders/denoiser.comp
> +	vec3 diffuse = c.direct_diffuse + c.indirect_diffuse + indirect_diffuse_sh;
Я добавляю все возможные виды пассов в rt.json, они все всегда запускаются и работают (за неимением какой-то системы пришлось так сделать). В своих пассах я проверяю флаги и в зависимости от этого сохраняют результаты в буфферы. В зависимости от флагов в этих буфферах либо нули, либо значения. Например, я проверяю флаги в diffuse_gi_sh_denoise_save.comp и забиваю нулями результаты работы других шейдеров, которые хочу отключить. Перенести ли мне эту логику в denoiser.comp? Наверное, это было бы более правильным и снизило бы число выборок в блюрах.

2024-12-18 17:20 UTC, LifeKILLED commented on ref/vk/shaders/denoiser.comp
> +	c.indirect_diffuse += imageLoad(indirect_diffuse_denoised_by_sh, p).rgb;
Тогда добавлю сюда ифчик, чтобы читать не все подряд буферы, а только тот, который влияет на картинку

2024-12-18 19:08 UTC, w23 commented on ref/vk/shaders/denoiser.comp
> +// Adding emissive_blend to the final color in the *incorrect* sRGB-? space. It makes
Это `.editorconfig` файл в корне репы шалит. Поменяй там `latin1` на `utf-8`. Это изменение есть у меня в рабочей ветке, пока не принёс в вулкан.

2024-12-19 16:16 UTC, LifeKILLED commented on ref/vk/shaders/denoiser.comp
> +	// TODO(or not todo): The �-Trous paper mentions that it should be c2 + d1 + d0, but
Починил

2024-12-19 16:16 UTC, LifeKILLED commented on ref/vk/shaders/denoiser.comp
> +// Adding emissive_blend to the final color in the *incorrect* sRGB-? space. It makes
Починил

2024-12-19 16:16 UTC, LifeKILLED commented on ref/vk/shaders/denoiser.comp
> -				c.direct_diffuse += imageLoad(light_poly_diffuse, p).rgb * direct_diffuse_scale;
Исправил

2024-12-19 16:19 UTC, LifeKILLED commented on ref/vk/shaders/denoiser.comp
> +	vec3 diffuse = c.direct_diffuse + c.indirect_diffuse + indirect_diffuse_sh;
Добавил в denoiser.comp проверки на флаги где только можно, изменения в этом коммите: https://github.com/w23/xash3d-fwgs/pull/750/commits/f19214e7bebded06f7494ba1c93d7bebd3c8086d

Также пропускаю флагом ненужный пасс indirect_diffuse_atrous1 при использовании своего метода

2024-12-19 20:09 UTC, w23 approved these changes

2024-12-19 20:10 UTC, merged